# Eksplorasi Data IRIS

Eksplorasi data merupakan langkah awal yang krusial dalam analisis data. Tahap ini bertujuan untuk memahami karakteristik, struktur, pola, dan kualitas dari suatu dataset sebelum melanjutkan ke pemodelan atau analisis yang lebih mendalam. 

Melalui eksplorasi ini, kita dapat mengenali isi data secara menyeluruh untuk menentukan metode analisis yang paling sesuai. Dalam catatan ini, saya menggunakan studi kasus **Dataset IRIS Flower**.

> **Sumber Data:** [Download IRIS.csv](./IRIS.csv)

## Persiapan Library

Sebelum memulai analisis, kita perlu memastikan pustaka (*library*) yang dibutuhkan sudah terpasang:

In [1]:
%pip install pandas seaborn matplotlib

Requirement already satisfied: pandas in c:\laragon\bin\python\python-3.10\lib\site-packages (2.3.3)
Requirement already satisfied: seaborn in c:\laragon\bin\python\python-3.10\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\laragon\bin\python\python-3.10\lib\site-packages (3.10.8)
Requirement already satisfied: numpy>=1.22.4 in c:\laragon\bin\python\python-3.10\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\laragon\bin\python\python-3.10\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\laragon\bin\python\python-3.10\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\laragon\bin\python\python-3.10\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\laragon\bin\python\python-3.10\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\laragon\bin\python\python-3.10\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Pratinjau Dataset

Dataset IRIS Flower terdiri dari 5 fitur dengan total 150 baris data. Berikut adalah tampilan data yang telah dimuat:

In [2]:
import pandas as pd

# Membaca data
df = pd.read_csv("IRIS.csv")
# Mengatur index agar mulai dari 1 
df.index = df.index + 1
# Menampilkan data
df

     sepal_length  sepal_width  petal_length  petal_width         species
1             5.1          3.5           1.4          0.2     Iris-setosa
2             4.9          3.0           1.4          0.2     Iris-setosa
3             4.7          3.2           1.3          0.2     Iris-setosa
4             4.6          3.1           1.5          0.2     Iris-setosa
5             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
146           6.7          3.0           5.2          2.3  Iris-virginica
147           6.3          2.5           5.0          1.9  Iris-virginica
148           6.5          3.0           5.2          2.0  Iris-virginica
149           6.2          3.4           5.4          2.3  Iris-virginica
150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

---
## Dimensi Data

Dimensi data memberitahu kita seberapa besar dataset yang sedang kita hadapi (Jumlah Baris vs Jumlah Kolom).

In [3]:
df.shape

(150, 5)

## Struktur dan Tipe Data

Kita perlu memastikan setiap kolom memiliki tipe data yang sesuai (misalnya: angka sebagai float, label sebagai object/string).

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

- Sepal/Petal Length & Width: Berupa float64 (Desimal), sudah tepat untuk perhitungan statistik.
- Species: Berupa object (Kategorikal), sebagai target klasifikasi.

## Pengecekan Data Duplikat

Data yang ganda dapat menyebabkan bias pada model.

In [5]:
df.duplicated().sum()

np.int64(3)

## Pengecekan Missing Value (Data Kosong)

Data yang kosong bisa merusak akurasi model. Kita harus memastikan setiap sel terisi.

In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Analisis: Jika hasilnya 0 untuk semua kolom, berarti dataset IRIS ini sangat bersih dan tidak memerlukan tahap pengisian data kosong (imputation).


## Deteksi Outlier (Pencilan Data)

Untuk mendeteksi outlier kita menggunakan tools orange data mining, dengan langkah sebagai berikut:
1. Buka Orange Data Mining.
2. Pilih widget "File" untuk memuat dataset IRIS.csv.
3. Sambungkan widget "File" ke widget "Outliers".
4. Lalu berikan 2 data table untuk melihat data yang dianggap outlier dan inlears.

![outlierIRIS](img/outlieriris.png)

Diatas adalah hasil dari deteksi outlier dengan menggunakan Orange data mining, dimana terdapat 15 data yang dianggap sebagai outlier, dan 135 data yang dianggap inlears. Namun, untuk dataset IRIS ini, kita tidak akan menghapus data outlier karena jumlahnya relatif kecil dan dapat memberikan informasi penting tentang variasi dalam data.

## Ringkasan Statistik

Untuk memahami sebaran angka pada setiap fitur numerik, berikut adalah ringkasan statistik deskriptif dari dataset tersebut:

In [7]:
# Menampilkan ringkasan statistik (Mean, Std Dev, Min, Max, dll)
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

> *Catatan: Gunakan tombol "Click to show" pada sel di atas jika ingin melihat kode Python yang digunakan untuk memproses tabel ini.*

---
## Kesimpulan Eksplorasi Data

Berdasarkan seluruh tahapan eksplorasi data yang telah dilakukan, berikut adalah kesimpulan utamanya:

- **Kualitas dan Integritas Data:**
   * **Data Sangat Bersih:** Tidak ditemukan adanya *missing values* (nilai kosong) pada seluruh fitur.
   * **Dataset Seimbang (*Balanced*):** Dataset memiliki distribusi kelas yang sempurna (masing-masing spesies memiliki 50 sampel).

- **Struktur dan Dimensi:**
   * Dataset memiliki dimensi **150 baris dan 5 kolom**.
   * Seluruh fitur numerik didefinisikan sebagai `float` dan target sebagai `object`.